<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<?php
//Product Collection

/*$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$collection = $productCollection->create()
            ->addAttributeToSelect('*')
			->addAttributeToFilter("visibility", "4")
            ->load();
			
			
			
			
//echo $collection->printLogQuery(true);			

foreach ($collection as $product){
     echo $product->getId().'  =  '.$product->getName().'<br>';
}  

$product = $objectManager->create("Magento\Catalog\Model\productFactory");
$pr = $product->create()->load(1); 
echo $pr->getName()."=".$pr->getFinalPrice();
echo "<pre>";
//print_r($pr);
echo "</pre>";

//Customer Collection

$customer = $objectManager->create("Magento\Customer\Model\ResourceModel\Customer\CollectionFactory");
$customerCollection = $customer->create()->load();
 
foreach($customerCollection as $cust){ 
	echo $cust->getId()." = ".$cust->getEmail()."<br />"; 
}

$cus = $objectManager->create("Magento\Customer\Model\CustomerFactory"); 
$c = $cus->create()->load(1); 

echo $c->getId()."==".$c->getName()." == ".$c->getEmail()."<br />";

//Order Collection 

$orderCollection = $objectManager->create("Magento\Sales\Model\ResourceModel\Order\CollectionFactory"); 
$orders = $orderCollection->create()->load(); 

foreach($orders as $order){ 
	echo $order->getId()." == ".$order->getIncrementId()."<br />"; 
}

$or = $objectManager->create("Magento\Sales\Model\OrderFactory");
$r = $or->create()->load(1);

echo $r->getIncrementId()."==";

//Category collection 
$categoryCollection = $objectManager->create("Magento\Catalog\Model\ResourceModel\Category\CollectionFactory"); 
$categories = $categoryCollection->create()->addAttributeToSelect("*")->load(); 



foreach($categories as $cat){ 
	//echo  "<pre>"; 
	//print_r($cat);
	//echo "</pre>"; //exit;
	echo $cat->getId()." == ".$cat->getName()."<br />";
}
 
$cats = $objectManager->create("Magento\Catalog\Model\CategoryFactory");
$c = $cats->create()->load(3);
echo $c->getName()." == ".$c->getDescription();  

 //$cat = $this->categoryFactory->create()->load(3)->getProductCollection()->addAttributeToSelect('*');*/
 
/*$custom = $objectManager->create('Prokarma\Hello\Model\Hello');
$cls = $custom->create()
            ->load(1);
			
			
			
			
//echo $collection->printLogQuery(true);			

foreach ($cls as $p){
     echo $p->getId().'  =  '.$p->getName().'<br>';
}  */

 
?>

<div class="block block-search"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-search')->toHtml();?>

    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
